title: Vania Pramuditha
logo: /assets/img/ava.png
description: Aspiring to apply analytical and problem-solving skills in a business analytics role to support data-driven decision-making. Strong expertise and versatile in data processing and analytics, currently enhancing skills through academic studies in business analytics.
show_download: false
theme: jekyll-theme-minimal
